name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "MODEL_NAME=${{ secrets.MODEL_NAME }}" >> $GITHUB_ENV
          echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV

      - name: Run unit tests
        run: python -m pytest tests/
